[program:script_comando]
directory=/home/cepedi/supervisor_rasp/script_comando
command=/home/cepedi/supervisor_rasp/script_comando/venv/bin/python -u main.py
autostart=true
autorestart=true
stderr_logfile=/var/log/script_comando.err.log
stdout_logfile=/var/log/script_comando.out.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=5
stderr_logfile_maxbytes=20MB
stderr_logfile_backups=5

[program:script_navegador]
directory=/home/cepedi/supervisor_rasp/script_navegador
command=/bin/bash /home/cepedi/supervisor_rasp/script_navegador/start-browser.sh
autostart=true
autorestart=true
stderr_logfile=/var/log/script_navegador.err.log
stdout_logfile=/var/log/script_navegador.out.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=5
stderr_logfile_maxbytes=20MB
stderr_logfile_backups=5
environment=DISPLAY=":0",XAUTHORITY="/home/cepedi/.Xauthority"
user=cepedi

[program:script_gerenciador]
directory=/home/cepedi/supervisor_rasp/script_gerenciador
command=/home/cepedi/supervisor_rasp/script_gerenciador/venv/bin/python -u main_v2.py
autostart=true
autorestart=true
startsecs=5
startretries=999
stderr_logfile=/var/log/script_gerenciador.err.log
stdout_logfile=/var/log/script_gerenciador.out.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=5
stderr_logfile_maxbytes=20MB
stderr_logfile_backups=5
user=cepedi

[program:script_camera]
directory=/home/cepedi/supervisor_rasp/script_camera
command=/home/cepedi/supervisor_rasp/script_camera/degirum_env/bin/python -u main.py
autostart=true
autorestart=true
startsecs=5
startretries=999
stopasgroup=true
killasgroup=true
environment=INTERFACE_GRAFICA=0
stderr_logfile=/var/log/script_camera.err.log
stdout_logfile=/var/log/script_camera.out.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=5
stderr_logfile_maxbytes=20MB
stderr_logfile_backups=5
user=cepedi
